channels:
  - defaults
  - conda-forge
  - fcakyon
dependencies:
  - python=3.7.5
  - pip=20.1
  - python-mss
  - numpy
  - craft-text-detector
  - tesseract
  - pytesseract
  - opencv
  - regex
  - pynput
  - pip:
    - rpaframework==7.*
